### ISSUE TITLE
issue about compiling sharp

### ISSUE THREAD

**Issue by Price1999a** [april1989/Incremental_Points_to_Analysis#3]
I'm trying to run SHARP, but I'm having some problems during the compilation phase.
Specifically, it is mentioned in SHARP's README file, import all projects (wala modules and this repositories) into a workspace of Eclipse.

However, after completing this step, Eclipse prompts a large number of errors. The problem seems to be that each module has not been correctly imported into the IDE, as shown in the figure below.

<img width="1056" alt="截屏2023-01-31 14 42 13" src="https://user-images.githubusercontent.com/32087147/215685891-9ce6ef6e-ac0f-44d2-ac49-cb62b4c607ae.png">

The import method I use is: right click in Package Explorer -> import... -> General -> Projects from Folder and Archiver.

Regarding this problem, how could we solve it?

**Comment by april1989** [comment]
Hi, 

I had this problem before. The thing is eclipse is not "smart", it cannot resolve the complex dependencies. 

You can try:
Project -> Clean -> clean all projects, eclipse should automatically rebuild the cleaned projects (if not, manually build them). 

If the above does not work, try: 
Project -> Clean -> clean each project according to this order: wala.util, wall.shrink, wala.core, wala.cast, wala.cast.java, increpta.origin, increpta.kcfa, increpta.obj, full.tests.
This solved the problem on my eclipse (Version: 2020-12 (4.18.0). Hope this can help you.

**Comment by Price1999a** [comment]
Hi,

I'm running into some new problems now.
In the module increpta.origin of SHARP, it seems that some classes that do not exist in WALA are imported?
For example: line 18 of `https://github.com/april1989/Incremental_Points_to_Analysis/blob/master/Sharp/edu.tamu.wala.increpta.origin/src/edu/tamu/wala/increpta/instancekey/IPAZeroXInstanceKeys.java` is importing NullConstantKey, I did not find it in the github repository corresponding to WALA (including the previous tag).
Similarly, there are some other details about dependencies.

So could you confirm the version of WALA that SHARP depends on?

![image](https://user-images.githubusercontent.com/32087147/219015130-a5807afa-3fb0-452d-8a7e-7a30b9356271.png)

**Comment by april1989** [comment]
The wala version I use is 1.5.2, here is the link https://github.com/wala/WALA/tree/R_1.5.2 or you can try maven. 

If it does not work, I can give you the wala projects I have, but let me know what is a good way to upload them, e.g., google drive.

**Comment by Price1999a** [comment]
I can use Google Drive.

Thank you very much.

**Comment by april1989** [comment]
I assume this is your email mf21330068@smail.nju.edu.cn?

**Comment by Price1999a** [comment]
Yes, this is the email address assigned to me by the university.

**Comment by april1989** [comment]
I’ll send you the link to the email.

Best regards,
Bozhen Liu

**Comment by Price1999a** [comment]
In fact, compared with https://github.com/wala/WALA/tree/R_1.5.2, the wala source code you provided does have some differences in details (such as the NullConstantKey I mentioned earlier).

In short, now in the IDE, the main() method of GitPteTest can finally run!

Many thanks for your kind and warm help.

**Comment by chhnb** [comment]
Hello, I have the same issue when running SHARP, like "Cannot resolve symbol 'NullConstantKey'".
Can you share the google drive link of the modified WALA which you are using or upload it to this repo?
Thanks very much.
@april1989
